name: Main

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: npm install + build
        run: |
          npm install bower
          npx bower install

      - name: create archive
        run: |
          mkdir moneta-web-${{ github.ref_name }}
          mv bower_components css images js templates index.html LICENSE moneta-web-${{ github.ref_name }}
          tar cvzf moneta-web-${{ github.ref_name }}.tar.gz moneta-web-${{ github.ref_name }}

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: moneta-web-${{ github.ref_name }}.tar.gz